### ISSUE TITLE
unexpected keyword argument 'tiled_decode'

### ISSUE THREAD

**Issue by ptits** [genmoai/mochi#38]
TypeError: MochiSingleGPUPipeline.__init__() got an unexpected keyword argument 'tiled_decode'

you should set decode_type properly I guess (in cli.py)

**Comment by xpeng** [comment]
same issue

**Comment by hansku** [comment]
Same:

python3 ./demos/gradio_ui.py --model_dir "weights"
* Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Launching with 1 GPUs. If you want to force single GPU mode use CUDA_VISIBLE_DEVICES=0.
Attention mode: sdpa
Traceback (most recent call last):
  File "/home/hk/models/.venv/lib/python3.10/site-packages/gradio/queueing.py", line 624, in process_events
    response = await route_utils.call_process_api(
  File "/home/hk/models/.venv/lib/python3.10/site-packages/gradio/route_utils.py", line 323, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/hk/models/.venv/lib/python3.10/site-packages/gradio/blocks.py", line 2018, in process_api
    result = await self.call_function(
  File "/home/hk/models/.venv/lib/python3.10/site-packages/gradio/blocks.py", line 1567, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "/home/hk/models/.venv/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/hk/models/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "/home/hk/models/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "/home/hk/models/.venv/lib/python3.10/site-packages/gradio/utils.py", line 846, in wrapper
    response = f(*args, **kwargs)
  File "/home/hk/models/demos/cli.py", line 66, in generate_video
    load_model()
  File "/home/hk/models/demos/cli.py", line 53, in load_model
    pipeline = klass(**kwargs)
TypeError: MochiSingleGPUPipeline.__init__() got an unexpected keyword argument 'tiled_decode'
MochiSingleGPUPipeline.__init__() got an unexpected keyword argument 'tiled_decode'

**Comment by ajayjain** [comment]
@ptits @xpeng Are you still having the issue? It should be fixed based on https://github.com/genmoai/models/issues/49
