### ISSUE TITLE
started but nothing happening 

### ISSUE THREAD

**Issue by ptits** [genmoai/mochi#6]
python3 -m mochi_preview.infer --prompt "A hand with delicate fingers picks up a bright yellow lemon from a wooden bowl filled with lemons and sprigs of mint against a peach-colored background. The hand gently tosses the lemon up and catches it, showcasing its smooth texture. A beige string bag sits beside the bowl, adding a rustic touch to the scene. Additional lemons, one halved, are scattered around the base of the bowl. The even lighting enhances the vibrant colors and creates a fresh, inviting atmosphere." --seed 1710977262 --cfg_scale 4.5 --model_dir .
2024-10-22 21:37:02,815 INFO worker.py:1786 -- Started a local Ray instance.
(T2VSynthMochiModel pid=911897) Timing init_process_group
(T2VSynthMochiModel pid=911979) Timing load_text_encs
(T2VSynthMochiModel pid=911901) Timing init_process_group [repeated 7x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/user-guides/configure-logging.html#log-deduplication for more options.)

and silence...  

    0   N/A  N/A    911901      C   ray::T2VSynthMochiModel.__init__           1366MiB |
|    0   N/A  N/A   3254768      C   venv/bin/python                            5334MiB |
|    1   N/A  N/A    911980      C   ray::T2VSynthMochiModel.__init__           1510MiB |
|    2   N/A  N/A    911897      C   ray::T2VSynthMochiModel.__init__           1510MiB |
|    3   N/A  N/A    911896      C   ray::T2VSynthMochiModel.__init__           1510MiB |
|    4   N/A  N/A    911891      C   ray::T2VSynthMochiModel.__init__           1510MiB |
|    5   N/A  N/A    911898      C   ray::T2VSynthMochiModel.__init__           1510MiB |
|    6   N/A  N/A    911979      C   ray::T2VSynthMochiModel.__init__           1510MiB |
|    7   N/A  N/A    911902      C   ray::T2VSynthMochiModel.__init__           1366MiB |

**Comment by ptits** [comment]
It is freezing here:

dist.init_process_group(
                    "nccl",
                    rank=local_rank,
                    world_size=world_size,
                    device_id=self.device,  # force non-lazy init
                )

**Comment by ved-genmo** [comment]
this will take about 2-40 seconds to initialize. Let me know if after waiting that long, if the issue still is occurring.

**Comment by ptits** [comment]
With my debug prints it always prints rank=2 and never goes to text encoder.

**Comment by bramvera** [comment]
yup me too

```
WARNING: Mochi requires at least 4xH100 GPUs, but only 2 GPU(s) are available.
Launching with 2 GPUs.
(T2VSynthMochiModel pid=41672) Timing init_process_group (can take 20-30 seconds)
(T2VSynthMochiModel pid=41590) Timing init_process_group (can take 20-30 seconds)
(T2VSynthMochiModel pid=41672) Timing load_text_encs
(T2VSynthMochiModel pid=41590) Timing load_text_encs
```
nothing happened more than 5 minutes

**Comment by janoschsimon** [comment]
i get this error (T2VSynthMochiModel pid=4512) Timing init_process_group (can take 20-30 seconds)
(T2VSynthMochiModel pid=4513) Timing load_text_encs
(T2VSynthMochiModel pid=4513) Timing load_vae
(T2VSynthMochiModel pid=4513) Timing init_process_group (can take 20-30 seconds)
(T2VSynthMochiModel pid=4512) Timing load_text_encs
(T2VSynthMochiModel pid=4513) Timing construct_dit
(T2VSynthMochiModel pid=4513) Exception raised in creation task: The actor died because of an error raised in its creation task, ray::T2VSynthMochiModel.__init__() (pid=4513, ip=172.17.0.3, actor_id=226cd3320f9f844251edf18201000000, repr=<mochi_preview.t2v_synth_mochi.T2VSynthMochiModel object at 0x708890b118a0>)
(T2VSynthMochiModel pid=4513)   File "/workspace/models/src/mochi_preview/t2v_synth_mochi.py", line 250, in __init__
(T2VSynthMochiModel pid=4513)     with open(dit_config_path, "r") as f:
(T2VSynthMochiModel pid=4513) FileNotFoundError: [Errno 2] No such file or directory: '/workspace/models//dit-config.yaml'
Traceback (most recent call last):
  File "/workspace/models/.venv/lib/python3.10/site-packages/gradio/queueing.py", line 624, in process_events
    response = await route_utils.call_process_api(
  File "/workspace/models/.venv/lib/python3.10/site-packages/gradio/route_utils.py", line 323, in call_process_api
    output = await app.get_blocks().process_api(
  File "/workspace/models/.venv/lib/python3.10/site-packages/gradio/blocks.py", line 2018, in process_api
    result = await self.call_function(
  File "/workspace/models/.venv/lib/python3.10/site-packages/gradio/blocks.py", line 1567, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "/workspace/models/.venv/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/workspace/models/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "/workspace/models/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "/workspace/models/.venv/lib/python3.10/site-packages/gradio/utils.py", line 846, in wrapper
    response = f(*args, **kwargs)
  File "/workspace/models/src/mochi_preview/infer.py", line 73, in generate_video
    load_model()
  File "/workspace/models/src/mochi_preview/infer.py", line 38, in load_model
    model = MochiWrapper(
  File "/workspace/models/src/mochi_preview/handler.py", line 25, in __init__
    ray.get(worker.__ray_ready__.remote())
  File "/workspace/models/.venv/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/workspace/models/.venv/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/workspace/models/.venv/lib/python3.10/site-packages/ray/_private/worker.py", line 2745, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/workspace/models/.venv/lib/python3.10/site-packages/ray/_private/worker.py", line 903, in get_objects
    raise value
ray.exceptions.ActorDiedError: The actor died because of an error raised in its creation task, ray::T2VSynthMochiModel.__init__() (pid=4513, ip=172.17.0.3, actor_id=226cd3320f9f844251edf18201000000, repr=<mochi_preview.t2v_synth_mochi.T2VSynthMochiModel object at 0x708890b118a0>)
  File "/workspace/models/src/mochi_preview/t2v_synth_mochi.py", line 250, in __init__
    with open(dit_config_path, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/models//dit-config.yaml'
